
export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    products: "Products",
    orders: "Orders",
    reviews: "Reviews",
    articles: "Articles",
    settings: "Settings",
    users: "Users",
    categories: "Categories",
    search: "Search...",
    add_product: "Add Product",
    edit_product: "Edit Product",
    add_category: "Add Category",
    edit_category: "Edit Category",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    view: "View",
    actions: "Actions",
    name_en: "Name (English)",
    name_ar: "Name (Arabic)",
    desc_en: "Description (English)",
    desc_ar: "Description (Arabic)",
    price: "Price",
    category: "Category",
    category_image: "Category Image",
    image_url: "Image URL",
    main_image: "Main Image",
    gallery: "Product Gallery",
    video_url: "Video URL (Optional)",
    sku: "SKU",
    stock: "Stock Quantity",
    customer: "Customer",
    status: "Status",
    total: "Total",
    date: "Date",
    replied: "Replied",
    moderate: "Moderate",
    title_en: "Title (English)",
    title_ar: "Title (Arabic)",
    content_en: "Content (English)",
    content_ar: "Content (Arabic)",
    branding: "Branding",
    social_media: "Social Media",
    store_info: "Store Information",
    payment_number: "Payment Phone Number",
    overview: "Dashboard Overview",
    total_sales: "Total Sales",
    total_orders: "Total Orders",
    new_customers: "New Customers",
    conversion: "Conversion Rate",
    language: "Language",
    logout: "Logout",
    rating: "Rating",
    comment: "Comment",
    approve: "Approve",
    hide: "Hide",
    reply: "Reply",
    add_article: "Add Article",
    edit_article: "Edit Article",
    author: "Author",
    featured_image: "Featured Image",
    add_image_url: "Add Image URL",
    remove: "Remove",
    login: "Login",
    email: "Email Address",
    password: "Password",
    sign_in: "Sign In",
    forgot_password: "Forgot Password?",
    remember_me: "Remember Me",
    welcome_back: "Welcome Back",
    add_review: "Add Review",
    edit_review: "Edit Review",
    customer_name: "Customer Name",
    customer_phone: "Phone Number",
    customer_email: "Customer Email",
    shipping_address: "Shipping Address",
    order_items: "Order Items",
    qty: "Qty",
    drivers_arrived: "Drivers Arrived",
    select_product: "Select Product",
    stars: "Stars",
    add_user: "Add User",
    edit_user: "Edit User",
    role: "Role",
    admin: "Admin",
    editor: "Editor",
    viewer: "Viewer",
    active: "Active",
    inactive: "Inactive",
    user_name: "Full Name"
  },
  ar: {
    dashboard: "لوحة التحكم",
    products: "المنتجات",
    orders: "الطلبات",
    reviews: "المراجعات",
    articles: "المقالات",
    settings: "الإعدادات",
    users: "المستخدمين",
    categories: "الفئات",
    search: "بحث...",
    add_product: "إضافة منتج",
    edit_product: "تعديل منتج",
    add_category: "إضافة فئة",
    edit_category: "تعديل فئة",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    view: "عرض",
    actions: "إجراءات",
    name_en: "الاسم (إنجليزي)",
    name_ar: "الاسم (عربي)",
    desc_en: "الوصف (إنجليزي)",
    desc_ar: "الوصف (عربي)",
    price: "السعر",
    category: "الفئة",
    category_image: "صورة الفئة",
    image_url: "رابط الصورة",
    main_image: "الصورة الرئيسية",
    gallery: "معرض الصور",
    video_url: "رابط الفيديو (اختياري)",
    sku: "وحدة حفظ المخزون",
    stock: "كمية المخزون",
    customer: "العميل",
    status: "الحالة",
    total: "الإجمالي",
    date: "التاريخ",
    replied: "تم الرد",
    moderate: "الإشراف",
    title_en: "العنوان (إنجليزي)",
    title_ar: "العنوان (عربي)",
    content_en: "المحتوى (إنجليزي)",
    content_ar: "المحتوى (عربي)",
    branding: "الهوية التجارية",
    social_media: "وسائل التواصل الاجتماعي",
    store_info: "معلومات المتجر",
    payment_number: "رقم هاتف الدفع",
    overview: "نظرة عامة على لوحة التحكم",
    total_sales: "إجمالي المبيعات",
    total_orders: "إجمالي الطلبات",
    new_customers: "عملاء جدد",
    conversion: "معدل التحويل",
    language: "اللغة",
    logout: "تسجيل الخروج",
    rating: "التقييم",
    comment: "التعليق",
    approve: "موافقة",
    hide: "إخفاء",
    reply: "رد",
    add_article: "إضافة مقال",
    edit_article: "تعديل مقال",
    author: "الكاتب",
    featured_image: "الصورة البارزة",
    add_image_url: "إضافة رابط صورة",
    remove: "إزالة",
    login: "تسجيل الدخول",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    sign_in: "دخول",
    forgot_password: "نسيت كلمة المرور؟",
    remember_me: "تذكرني",
    welcome_back: "مرحباً بعودتك",
    add_review: "إضافة مراجعة",
    edit_review: "تعديل مراجعة",
    customer_name: "اسم العميل",
    customer_phone: "رقم الهاتف",
    customer_email: "بريد العميل",
    shipping_address: "عنوان الشحن",
    order_items: "عناصر الطلب",
    qty: "الكمية",
    drivers_arrived: "وصل السائقون",
    select_product: "اختر المنتج",
    stars: "النجوم",
    add_user: "إضافة مستخدم",
    edit_user: "تعديل مستخدم",
    role: "الدور",
    admin: "مسؤول",
    editor: "محرر",
    viewer: "مشاهد",
    active: "نشط",
    inactive: "غير نشط",
    user_name: "الاسم الكامل"
  }
};
